CREATE TABLE [dbo].[OKVED] (
    [id]        INT           IDENTITY (1, 1) NOT NULL,
    [OKVEDName] VARCHAR (500) NOT NULL,
    CONSTRAINT [PK_OKVED] PRIMARY KEY CLUSTERED ([id] ASC),
    CONSTRAINT [IX_OKVED] UNIQUE NONCLUSTERED ([OKVEDName] ASC)
);

